<?php

/**
 * @file
 * Internationalization (i18n) submodule: Multilingual Forschungsatlas categories
 */

/**
 * Implements hook_menu().
 *
 * Add translate tab to categories config.
 */
function i18n_forschungsatlas_intersubject_menu() {
  $items[FORSCHUNGSATLAS_CONFIG_PATH .'/categories/intersubjects/%forschungsatlas_intersubject/translate'] = array(
    'title' => 'Translate',
    'access callback' => 'i18n_forschungsatlas_intersubject_translate_tab_access',
    'page callback' => 'i18n_string_object_translate_page',
    'page arguments' => array('forschungsatlas_intersubject', 5),
    'type' => MENU_LOCAL_TASK,
    'weight' => 10,
  );
  $items[FORSCHUNGSATLAS_CONFIG_PATH .'/categories/intersubjects/%forschungsatlas_intersubject/translate/%language'] = array(
    'title' => 'Translate',
    'access callback' => 'i18n_forschungsatlas_intersubject_translate_tab_access',
    'page callback' => 'i18n_string_object_translate_page',
    'page arguments' => array('forschungsatlas_intersubject', 5, 7),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Menu access callback function.
 */
function i18n_forschungsatlas_intersubject_translate_tab_access() {
  return user_access('administer nefo configuration');
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function i18n_forschungsatlas_intersubject_form_forschungsatlas_admin_intersubject_delete_confirm_alter(&$form, &$form_state) {
  $form['#submit'][] = 'i18n_forschungsatlas_intersubject_form_forschungsatlas_admin_intersubject_delete_confirm_submit';
}

/**
 * Remove strings for deleted categories.
 */
function i18n_forschungsatlas_intersubject_form_forschungsatlas_admin_intersubject_delete_confirm_submit(&$form, $form_state) {
  $isid = $form['isid']['#value']['isid'];
  i18n_string_remove("forschungsatlas_intersubject:interdisciplinarysubject:$isid:name");
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function i18n_forschungsatlas_intersubject_form_forschungsatlas_admin_intersubject_form_alter(&$form, &$form_state) {
    $form['actions']['translate'] = array(
    '#type' => 'submit',
    '#name'   => 'save_translate',
    '#value' => t('Save and translate'),
  );
  $form['#submit'][] = 'i18n_forschungsatlas_intersubject_form_forschungsatlas_admin_intersubject_form_submit';
}

/**
 * Remove strings for edited/added interdisciplinary subject.
 */
function i18n_forschungsatlas_intersubject_form_forschungsatlas_admin_intersubject_form_submit($form, &$form_state) {
  $intersubject = $form_state['values'];
  i18n_string_update(array('forschungsatlas_intersubject', 'interdisciplinarysubject', $intersubject['isid'], 'name'), $intersubject['name']);
  if ($form_state['triggering_element']['#name'] == 'save_translate') {
    $form_state['redirect'] = FORSCHUNGSATLAS_CONFIG_PATH .'/categories/intersubjects/' . $intersubject['isid'] . '/translate';
  }
}

